### ISSUE TITLE
scope-statement

### ISSUE THREAD

**Issue by sudo-eddy** [sudo-eddy/ecommerce-group-fall-22#1]
Team,

Please review the scope statement, the goal is to submit this assignment by Monday 9/27 along with the first two weekly reports. 
[scope-statement .pdf](https://github.com/sudo-eddy/ecommerce-group-fall-22/files/7232448/scope-statement.pdf)

**Comment by pthom4** [comment]
The scope statement looks good.
Is this what we would submit as report #1 for review by the Professor.
