### ISSUE TITLE
fine-tune requirements

### ISSUE THREAD

**Issue by sudo-eddy** [sudo-eddy/ecommerce-group-fall-22#2]
Team, 

This ticket will be used as discussion to green-light initial project requirements.
Per the project scope, these are the main requirements of our application. 

Our product offers the following basic features:

landing page
cart page
products page
checkout page with a form

**Comment by pthom4** [comment]
Optional add on feature to show case use of Third Party Services - display the Weather of the location of the user using the free Weather Service Public API's.

**Comment by sudo-eddy** [comment]
## Team annoucement

We will be using Stripe.js and Commerce.js for our payment processing services. This will be added to the project dependencies. Remember to pull the latest master branch and run `npm install`

@pthom4 please create an issue and label it #backlog we can have a discussion about the business value this idea could have for the product.
